const buttonsData = {
  Backquote: { en: ['`', '~'], ru: ['Ё', 'ё'], class: 'button-key_theme_dark' },
  Digit1: { en: ['1', '!'], ru: ['1', '!'] },
  Digit2: { en: ['2', '@'], ru: ['2', '"'] },
  Digit3: { en: ['3', '#'], ru: ['3', '№'] },
  Digit4: { en: ['4', '$'], ru: ['4', ';'] },
  Digit5: { en: ['5', '%'], ru: ['5', '%'] },
  Digit6: { en: ['6', '^'], ru: ['5', ':'] },
  Digit7: { en: ['7', '&'], ru: ['7', '?'] },
  Digit8: { en: ['8', '*'], ru: ['8', '*'] },
  Digit9: { en: ['9', '('], ru: ['9', '('] },
  Digit0: { en: ['0', ')'], ru: ['0', ')'] },
  Minus: { en: ['-', '_'], ru: ['-', '_'] },
  Equal: { en: ['=', '+'], ru: ['=', '+'] },
  Backspace: { en: ['Backspace'], ru: ['Backspace'], class: 'button-key_theme_dark button-key_long' },
  Tab: { en: ['Tab'], ru: ['Tab'], class: 'button-key_theme_dark button-key_middle' },
  KeyQ: { en: ['Q', 'q'], ru: ['Й', 'й'] },
  KeyW: { en: ['W', 'w'], ru: ['Ц', 'ц'] },
  KeyE: { en: ['E', 'e'], ru: ['У', 'у'] },
  KeyR: { en: ['R', 'r'], ru: ['К', 'к'] },
  KeyT: { en: ['T', 't'], ru: ['Е', 'е'] },
  KeyY: { en: ['Y', 'y'], ru: ['Н', 'н'] },
  KeyU: { en: ['U', 'u'], ru: ['Г', 'г'] },
  KeyI: { en: ['I', 'i'], ru: ['Ш', 'ш'] },
  KeyO: { en: ['O', 'o'], ru: ['Щ', 'щ'] },
  KeyP: { en: ['P', 'p'], ru: ['З', 'з'] },
  BracketLeft: { en: ['['], ru: ['Х', 'х'] },
  BracketRight: { en: [']'], ru: ['Ъ', 'ъ'] },
  Backslash: { en: ['\\', '|'], ru: ['\\', '/'] },
  Delete: { en: ['Del'], ru: ['Del'], class: 'button-key_theme_dark button-key_middle' },
  CapsLock: { en: ['CapsLock '], ru: ['CapsLock '], class: 'button-key_theme_dark button-key_long' },
  KeyA: { en: ['A', 'a'], ru: ['Ф', 'ф'] },
  KeyS: { en: ['S', 's'], ru: ['Ы', 'ы'] },
  KeyD: { en: ['D', 'd'], ru: ['В', 'в'] },
  KeyF: { en: ['F', 'f'], ru: ['А', 'а'] },
  KeyG: { en: ['G', 'g'], ru: ['П', 'п'] },
  KeyH: { en: ['H', 'h'], ru: ['Р', 'р'] },
  KeyJ: { en: ['J', 'j'], ru: ['О', 'о'] },
  KeyK: { en: ['K', 'k'], ru: ['Л', 'л'] },
  KeyL: { en: ['L', 'l'], ru: ['Д', 'д'] },
  Semicolon: { en: [';', ':'], ru: ['Ж', 'ж'] },
  Quote: { en: ["'", '"'], ru: ['Э', 'э'] },
  Enter: { en: ['Enter'], ru: ['Enter'], class: 'button-key_theme_dark button-key_grow' },
  ShiftLeft: { en: ['Shift'], ru: ['Shift'], class: 'button-key_theme_dark button-key_long' },
  Backslash1: { en: ['\\', '|'], ru: ['\\', '/'] },
  KeyZ: { en: ['Z', 'z'], ru: ['Я', 'я'] },
  KeyX: { en: ['X', 'x'], ru: ['Ч', 'ч'] },
  KeyC: { en: ['C', 'c'], ru: ['С', 'с'] },
  KeyV: { en: ['V', 'v'], ru: ['М', 'м'] },
  KeyB: { en: ['B', 'b'], ru: ['И', 'и'] },
  KeyN: { en: ['N', 'n'], ru: ['Т', 'т'] },
  KeyM: { en: ['M', 'm'], ru: ['Ь', 'ь'] },
  Comma: { en: [',', '<'], ru: ['б', 'б'] },
  Period: { en: ['.', '>'], ru: ['ю', 'ю'] },
  Slash: { en: ['/', '?'], ru: ['.', ','] },
  ArrowUp: { en: ['⬆'], ru: ['⬆'], class: 'button-key_theme_dark' },
  ShiftRight: { en: ['Shift'], ru: ['Shift'], class: 'button-key_theme_dark' },
  ControlLeft: { en: ['Ctrl'], ru: ['Ctrl'], class: 'button-key_theme_dark button-key_grow' },
  OsLeft: { en: ['Win'], ru: ['Win'], class: 'button-key_theme_dark' },
  AltLeft: { en: ['Alt'], ru: ['Alt'], class: 'button-key_theme_dark' },
  Space: { en: [''], ru: [''], class: 'button-key_space' },
  AltRight: { en: ['Alt'], ru: ['Alt'], class: 'button-key_theme_dark' },
  ControlRight: { en: ['Ctrl'], ru: ['Ctrl'], class: 'button-key_theme_dark button-key_grow' },
  ArrowLeft: { en: ['⬅'], ru: ['⬅'], class: 'button-key_theme_dark' },
  ArrowDown: { en: ['⬇'], ru: ['⬇'], class: 'button-key_theme_dark' },
  ArrowRight: { en: ['➡'], ru: ['➡'], class: 'button-key_theme_dark' },
};

export default buttonsData;
