const buttonsData = {
  Backquote: { en: ['~', '`'], ru: ['ё', 'Ё'], class: 'button-key_theme_dark' },
  Digit1: { en: ['1', '!'], ru: ['1', '!'] },
  Digit2: { en: ['2', '@'], ru: ['2', '"'] },
  Digit3: { en: ['#', '3'], ru: ['3', '№'] },
  Digit4: { en: ['$', '4'], ru: ['4', ';'] },
  Digit5: { en: ['%', '5'], ru: ['5', '%'] },
  Digit6: { en: ['^', '6'], ru: ['5', ':'] },
  Digit7: { en: ['&', '7'], ru: ['7', '?'] },
  Digit8: { en: ['*', '8'], ru: ['8', '*'] },
  Digit9: { en: ['(', '9'], ru: ['9', '('] },
  Digit0: { en: [')', '0'], ru: ['0', ')'] },
  Minus: { en: ['_', '-'], ru: ['_', '-'] },
  Equal: { en: ['+', '='], ru: ['+', '='] },
  Backspace: { en: ['Backspace'], ru: ['Backspace'], class: 'button-key_theme_dark button-key_long' },
  Tab: { en: ['Tab'], ru: ['Tab'], class: 'button-key_theme_dark button-key_middle' },
  KeyQ: { en: ['q', 'Q'], ru: ['й', 'Й'] },
  KeyW: { en: ['w', 'W'], ru: ['ц', 'Ц'] },
  KeyE: { en: ['e', 'E'], ru: ['у', 'У'] },
  KeyR: { en: ['r', 'R'], ru: ['к', 'К'] },
  KeyT: { en: ['t', 'T'], ru: ['е', 'Е'] },
  KeyY: { en: ['y', 'Y'], ru: ['н', 'Н'] },
  KeyU: { en: ['u', 'U'], ru: ['г', 'Г'] },
  KeyI: { en: ['i', 'I'], ru: ['ш', 'Ш'] },
  KeyO: { en: ['o', 'O'], ru: ['щ', 'Щ'] },
  KeyP: { en: ['p', 'P'], ru: ['з', 'З'] },
  BracketLeft: { en: ['['], ru: ['Х', 'х'] },
  BracketRight: { en: [']'], ru: ['ъ', 'Ъ'] },
  Backslash: { en: ['|', '\\'], ru: ['|', '\\'] },
  Delete: { en: ['Del'], ru: ['Del'], class: 'button-key_theme_dark button-key_middle' },
  CapsLock: { en: ['CapsLock '], ru: ['CapsLock '], class: 'button-key_theme_dark button-key_long' },
  KeyA: { en: ['a', 'A'], ru: ['ф', 'Ф'] },
  KeyS: { en: ['s', 'S'], ru: ['ы', 'Ы'] },
  KeyD: { en: ['d', 'D'], ru: ['в', 'В'] },
  KeyF: { en: ['f', 'F'], ru: ['а', 'А'] },
  KeyG: { en: ['g', 'G'], ru: ['п', 'П'] },
  KeyH: { en: ['h', 'H'], ru: ['р', 'Р'] },
  KeyJ: { en: ['j', 'J'], ru: ['о', 'О'] },
  KeyK: { en: ['k', 'K'], ru: ['л', 'Л'] },
  KeyL: { en: ['l', 'L'], ru: ['д', 'Д'] },
  Semicolon: { en: [':', ';'], ru: ['ж', 'Ж'] },
  Quote: { en: ['"', "'"], ru: ['э', 'Э'] },
  Enter: { en: ['Enter'], ru: ['Enter'], class: 'button-key_theme_dark button-key_grow' },
  ShiftLeft: { en: ['Shift'], ru: ['Shift'], class: 'button-key_theme_dark button-key_long' },
  Backslash1: { en: ['\\', '|'], ru: ['\\', '/'] },
  KeyZ: { en: ['z', 'Z'], ru: ['я', 'Я'] },
  KeyX: { en: ['x', 'X'], ru: ['ч', 'Ч'] },
  KeyC: { en: ['c', 'C'], ru: ['с', 'С'] },
  KeyV: { en: ['v', 'V'], ru: ['м', 'М'] },
  KeyB: { en: ['b', 'B'], ru: ['и', 'И'] },
  KeyN: { en: ['n', 'N'], ru: ['т', 'Т'] },
  KeyM: { en: ['m', 'M'], ru: ['ь', 'Ь'] },
  Comma: { en: ['<', ','], ru: ['б', 'Б'] },
  Period: { en: ['>', '.'], ru: ['ю', 'Ю'] },
  Slash: { en: ['?', '/'], ru: [',', '.'] },
  ArrowUp: { en: ['⬆'], ru: ['⬆'], class: 'button-key_theme_dark' },
  ShiftRight: { en: ['Shift'], ru: ['Shift'], class: 'button-key_theme_dark' },
  ControlLeft: { en: ['Ctrl'], ru: ['Ctrl'], class: 'button-key_theme_dark button-key_grow' },
  OsLeft: { en: ['Win'], ru: ['Win'], class: 'button-key_theme_dark' },
  AltLeft: { en: ['Alt'], ru: ['Alt'], class: 'button-key_theme_dark' },
  Space: { en: [' '], ru: [' '], class: 'button-key_space' },
  AltRight: { en: ['Alt'], ru: ['Alt'], class: 'button-key_theme_dark' },
  ControlRight: { en: ['Ctrl'], ru: ['Ctrl'], class: 'button-key_theme_dark button-key_grow' },
  ArrowLeft: { en: ['⬅'], ru: ['⬅'], class: 'button-key_theme_dark' },
  ArrowDown: { en: ['⬇'], ru: ['⬇'], class: 'button-key_theme_dark' },
  ArrowRight: { en: ['➡'], ru: ['➡'], class: 'button-key_theme_dark' },
};

export default buttonsData;
