const buttonsData = {
  Backquote: { en: ['`', '~'], ru: ['ё', 'Ё'] },
  Digit1: { en: ['1', '!'], ru: ['1', '!'] },
  Digit2: { en: ['2', '@'], ru: ['2', '"'] },
  Digit3: ['3', '#', '№'],
  Digit4: ['4', '$', ';'],
  Digit5: ['5', '%'],
  Digit6: ['6', '^', ':'],
  Digit7: ['7', '&', '?'],
  Digit8: ['8', '*'],
  Digit9: ['9', '('],
  Digit0: ['0', ')'],
  Minus: ['-', '_'],
  Equal: ['=', '+'],
  Backspace: ['Backspace'],
  keyQ: ['Q'],
  keyW: ['W'],
  keyE: ['E'],
  keyR: ['R'],
  keyT: ['T'],
  keyY: ['Y'],
  keyU: ['U'],
  keyI: ['I'],
  keyO: ['O'],
  keyP: ['P'],
  BracketLeft: ['['],
  BracketRight: [']'],
  Backslash: ['/', '|', '/'],
};

export default buttonsData;
